version: '3.3'
volumes:
  pg_data:

services:
  db:
    image: postgres
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  devops_demo:
    build: ./
    env_file: ./.env
    command: ["./wait-for-it.sh", "$DB_HOST:$DB_PORT", "--", "./cmd.sh"]
    volumes:
      - ./compose/cmd.sh:/app/cmd.sh
      - ./compose/wait-for-it.sh:/app/wait-for-it.sh

  gateway:
    image: nginx
    ports:
      - 9999:80
    volumes:
      - ./compose/nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - db
      - devops_demo
